### PR TITLE
Vc 115/live editor support

### PR DESCRIPTION
**Pull request by Deepak-Kharah**

### CODE REVIEW

**Review by contentstackMridul — COMMENTED** [review]
Hey @hiteshshetty-dev @Deepak-Kharah, in our npm publish workflow, we are currently using node 16 to create a build and publish it. I think we should bump up the node version used to publish this package.

**Comment by Deepak-Kharah** [comment]
Sure, @contentstackMridul. Let's keep it same as what we use for development.

**Review by hiteshshetty-dev — COMMENTED** [review]
LGTM!!

**Review by hiteshshetty-dev — APPROVED** [review]

**Review by contentstackMridul — APPROVED** [review]
LGTM

**Review by aravindbuilt — APPROVED** [review]

**Pull request merged**
